
name: Container

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
         context: .
         file: Dockerfile
         push: true
         tags: sogno/dpsim:api
