
name: Container

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Generate tag name
        run: |
            if [[ "${{ github.repository_owner }}" != "sogno-platform" ]];
            then
                echo "TAG_NAME=sogno/dpsim:api-${{ github.repository_owner }}" >> $GITHUB_ENV
            else
                echo "TAG_NAME=sogno/dpsim:api" >> $GITHUB_ENV
            fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
         context: .
         file: Dockerfile
         push: true
         tags: "${{ env.TAG_NAME }}"
