name: Docs

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docs:

    runs-on: ubuntu-latest
    name: Build docs
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Build docs
        run: cargo doc --no-deps

      - name: Create openapi.json
        run: ./scripts/generate_openapi.sh

      - name: Create doc redirect
        uses: "finnp/create-file-action@master"
        env:
            FILE_NAME: "target/doc/index.html"
            FILE_DATA: "<meta http-equiv=\"refresh\" content=\"0; URL=dpsim_api/index.html\" />"

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: target/doc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to get a token
          MESSAGE: "Build documentation: ({sha}) {msg}"
